#!/usr/bin/env python3
"""
Generate Figure 1: Tension Evolution Visualization
Shows progressive reduction of Hubble tension through 5 stages + conservative scenario

Data source: data/tension_evolution.csv
Output: figures/figure1_tension_evolution.png (publication quality)
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import json

# Planck 2018 values
PLANCK_H0 = 67.36
PLANCK_SIGMA = 0.54

def create_tension_evolution_figure():
    """Create publication-quality tension evolution figure"""

    # Load data from CSV (single source of truth, generated by calculate_tension_evolution.py)
    data = pd.read_csv('data/tension_evolution.csv', comment='#')

    # Read values from CSV
    h0_values = data['H0_km_s_Mpc'].tolist()
    sigma_values = data['Sigma_km_s_Mpc'].tolist()
    tension_values = data['Tension_sigma'].tolist()

    # Round tension for display labels (manuscript uses 1 decimal place)
    tension_display = [round(t, 1) for t in tension_values]

    stages = [str(i+1) for i in range(len(h0_values))]
    stage_labels = [
        '1: Stat. only',
        '2: Quoted sys.\n+ stat.',
        '3: Scenario A ZP',
        '4: + Period dist.',
        '5: + Metallicity\n+ Realistic σ'
    ]

    # Create figure
    fig, ax = plt.subplots(figsize=(10, 6))

    # X positions
    x_pos = np.arange(len(stages))

    # Plot Planck band (horizontal)
    ax.axhspan(PLANCK_H0 - PLANCK_SIGMA, PLANCK_H0 + PLANCK_SIGMA,
               alpha=0.2, color='blue', zorder=1, label='Planck 2018')
    ax.axhline(PLANCK_H0, color='blue', linestyle='--', linewidth=1.5,
               alpha=0.7, zorder=2)

    # Plot tension evolution
    colors = ['red', 'orange', 'gold', 'yellowgreen', 'green']
    # Different marker shapes for grayscale compatibility
    markers = ['o', 's', '^', 'D', 'v']  # circle, square, triangle-up, diamond, triangle-down

    # Connect stages 1-5 with line (no markers on connecting line to avoid clutter)
    ax.plot(x_pos, h0_values, '-', color='darkred', linewidth=2,
            zorder=3, label='Tension evolution (Scenario A + Prior 1 baseline)')

    # Error bars with distinct markers for grayscale compatibility
    for i in range(len(stages)):
        ax.errorbar(x_pos[i], h0_values[i], yerr=sigma_values[i],
                   fmt=markers[i], color=colors[i], markersize=8, capsize=5,
                   capthick=2, linewidth=2, zorder=4, markerfacecolor=colors[i],
                   markeredgecolor='black', markeredgewidth=0.5)

        # Add tension value labels
        ax.text(x_pos[i], h0_values[i] + sigma_values[i] + 0.5,
               f'{tension_display[i]:.1f}σ',
               ha='center', va='bottom', fontsize=10, fontweight='bold',
               color=colors[i])

    # Add arrows with ΔH₀ and Δσ labels between stages
    arrow_props = dict(arrowstyle='->', lw=1.5, alpha=0.6)

    # Stage 1→2: σ increases (no H₀ change)
    mid_x = (x_pos[0] + x_pos[1]) / 2
    ax.annotate('', xy=(x_pos[1], 72.5), xytext=(x_pos[0], 72.5),
                arrowprops=dict(arrowstyle='->', lw=1.2, alpha=0.5, color='gray'))
    ax.text(mid_x, 72.8, 'σ: +0.51', ha='center', va='bottom',
            fontsize=8, style='italic', color='darkgray')

    # Stage 3→4: Period correction (ΔH₀ = -2.5)
    mid_x = (x_pos[2] + x_pos[3]) / 2
    ax.annotate('', xy=(x_pos[3], 71.8), xytext=(x_pos[2], 71.8),
                arrowprops=dict(arrowstyle='->', lw=1.5, alpha=0.6, color='darkgreen'))
    ax.text(mid_x, 72.1, 'ΔH₀: −2.5 (Period)', ha='center', va='bottom',
            fontsize=8, fontweight='bold', color='darkgreen')
    ax.text(mid_x, 71.5, 'σ: +0.34', ha='center', va='top',
            fontsize=7, style='italic', color='darkgray')

    # Stage 4→5: Metallicity + realistic σ (ΔH₀ = -1.0)
    mid_x = (x_pos[3] + x_pos[4]) / 2
    ax.annotate('', xy=(x_pos[4], 70.0), xytext=(x_pos[3], 70.0),
                arrowprops=dict(arrowstyle='->', lw=1.5, alpha=0.6, color='darkblue'))
    ax.text(mid_x, 70.3, 'ΔH₀: −1.0 (Metallicity)', ha='center', va='bottom',
            fontsize=8, fontweight='bold', color='darkblue')
    ax.text(mid_x, 69.7, 'σ: +0.24', ha='center', va='top',
            fontsize=7, style='italic', color='darkgray')

    # Add 3σ threshold line
    threshold_h0 = PLANCK_H0 + 3 * np.sqrt(PLANCK_SIGMA**2 + 1.89**2)
    ax.axhline(threshold_h0, color='red', linestyle=':', linewidth=1.5,
               alpha=0.5, label='3σ threshold')

    # Formatting
    ax.set_ylabel('H₀ (km s⁻¹ Mpc⁻¹)', fontsize=12, fontweight='bold')
    ax.set_title('Tension Evolution: Progressive Reduction Through Realistic Systematics',
                fontsize=14, fontweight='bold', pad=20)

    ax.set_xticks(x_pos)
    ax.set_xticklabels(stage_labels, fontsize=9)
    ax.set_ylim(64, 77)
    ax.grid(True, alpha=0.3, linestyle='--')

    # Legend
    ax.legend(loc='upper right', fontsize=10, framealpha=0.9)

    # Add annotations
    ax.text(0.02, 0.98,
           f'Planck: H₀ = {PLANCK_H0:.2f} ± {PLANCK_SIGMA:.2f} km s⁻¹ Mpc⁻¹',
           transform=ax.transAxes, fontsize=9, va='top',
           bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.5))

    ax.text(0.98, 0.02,
           f'Reduced from ~6σ to ~1–2σ\nBaseline: {tension_display[0]:.1f}σ → {tension_display[-1]:.1f}σ (Scenario A + Prior 1)\nFull range: 0.2σ to 1.7σ across scenarios',
           transform=ax.transAxes, fontsize=9, ha='right', va='bottom',
           bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.5))

    plt.tight_layout()

    # Save both PNG and PDF
    plt.savefig('figures/figure1_tension_evolution.png', dpi=300, bbox_inches='tight')
    plt.savefig('figures/figure1_tension_evolution.pdf', bbox_inches='tight')

    print("✅ Figure 1 generated successfully:")
    print("   - figures/figure1_tension_evolution.png (300 DPI)")
    print("   - figures/figure1_tension_evolution.pdf")

    # Save JSON metadata for verification system
    metadata = {
        "figure_id": "figure1_tension_evolution",
        "filename": "figure1_tension_evolution.pdf",
        "key_values": {
            "stage_1_h0": h0_values[0],
            "stage_1_sigma": sigma_values[0],
            "stage_1_tension": round(tension_values[0], 1),
            "stage_5_h0": h0_values[-1],
            "stage_5_sigma": sigma_values[-1],
            "stage_5_tension": round(tension_values[-1], 1),
            "reduction_factor": round(tension_values[0] / tension_values[-1], 1),
            "planck_h0": PLANCK_H0,
            "planck_sigma": PLANCK_SIGMA
        }
    }

    with open('figures/figure1_tension_evolution_metadata.json', 'w') as f:
        json.dump(metadata, f, indent=2)
    print("   - figures/figure1_tension_evolution_metadata.json")

    plt.close()

if __name__ == '__main__':
    create_tension_evolution_figure()
